### ISSUE TITLE
(Feature Request) Ability to add programs in the right-side Application panel

### ISSUE THREAD

**Issue by ghost** [winegui/WineGUI#10]
First of all I would like to thank everyone who has contributed to this project for all their dedication and hardwork.

WineGUI is a great piece of software, however, the only QoL feature I feel it is missing is the ability to add/remove Wine .desktop entries and have the ability to bookmark/pin/create a shortcut to a .bat or .exe file to the Applications menu on the right side.

As you can see in the picture attached below, i have the original GTA - VC installed, I have copied over reVC (source port) 
The reVC.exe executable runs and works flawlessly but everytime I want to use it I need to manually start Wine Explorer and navigate to the install directory.

I am unable to find any user-friendly way to create .desktop entries of the reVC.exe to my Applications menu (I know I can manually create .desktop entries)

Thus, I think It would be a massive QoL addition for WineGUI to include the features mentioned above. (The ability to pin executables to the right-hand side Applications menu would suffice)

![Screenshot from 2023-01-29 19-03-15](https://user-images.githubusercontent.com/120107145/215328088-798504f7-ecbf-4ede-967e-f2955f41c49f.png)

**Comment by melroy89** [comment]
> First of all I would like to thank everyone who has contributed to this project for all their dedication and hardwork.

Thank you so much, would be mainly me, since there are no other source-code contributors (yet).

> As you can see in the picture attached below, i have the original GTA - VC installed

So the screenshot shows GTA VC already, but not your "reVC" version, because that is not installed using an installer. But manually copied, right?

That make sense indeed. I will see if I can make an button to create a menu item by selecting the executable and the *.desktop file will then be created for you.

**Comment by ghost** [comment]
Thank you for replying, I truly cannot express in words how much your program has helped me migrate to linux.

Another feature that would be nice to have, but is not really critical or necessary, is right-click menu integration in file managers (mime-type association) like how vanilla wine from wineHQ does (in attached screenshot)

it would be very useful if there was a right-click menu for WineGUI that let you under what prefix to run any given .bat/.exe/.msi as (attached mock edit of what it might look like)

![Screenshot from 2023-02-02 00-14-23](https://user-images.githubusercontent.com/120107145/216134725-1b2449ab-34ac-4cf3-bcde-97ee0a3525e2.png)
![Screenshot from 2023-02-02 00-25-47](https://user-images.githubusercontent.com/120107145/216134765-b33f3f7f-219c-4c75-9adc-ff8be539beb5.png)

**Comment by melroy89** [comment]
I also created the feature upstream on my GitLab instance: https://gitlab.melroy.org/melroy/winegui/-/issues/30

**Comment by melroy89** [comment]
PR created (draft..): https://gitlab.melroy.org/melroy/winegui/-/merge_requests/17

**Comment by melroy89** [comment]
Ability to add programs/shortcuts to the application list is added in v2.0.0!

**Comment by melroy89** [comment]
> Another feature that would be nice to have, but is not really critical or necessary, is right-click menu integration in file managers (mime-type association) like how vanilla wine from wineHQ does (in attached screenshot)
> 
> it would be very useful if there was a right-click menu for WineGUI that let you under what prefix to run any given .bat/.exe/.msi as (attached mock edit of what it might look like)

Let's create a new issue for that feature.
