### ISSUE TITLE
(Feature Request) Command Line Interface

### ISSUE THREAD

**Issue by rdnckreaper** [winegui/WineGUI#12]
My header may be completely wrong for what I am thinking so I will describe it here.
What I am looking for is a way to write a shell script that when ran will open up a particular program in a particular 'container' inside winegui.
I set up winegui with a game server application designed for windows and it works perfectly. The problem is that if I attempt to open the server.exe without going through winegui it will attempt to run in regular wine which doesn't work for some reason.

**Comment by melroy89** [comment]
Try to execute your application like so:

```sh
WINEPREFIX=/home/username/.winegui/prefixes/name wine /path/to/your/server.exe
```

So that will then use the `WINEPREFIX` environment variable from bare wine executable. Which is the standard of using plain wine command line 😊. 

Meaning Winegui will not try to vendor lock you in the application. Allowing you full access to the wine command line as well.

**Comment by melroy89** [comment]
@rdnckreaper And did that work for you?

**Comment by rdnckreaper** [comment]
Sorry for the late reply I have really busy between work and my wine
issues...lol
Unfortunately, that did not work for the scenario.
My experience with wine has always been limited to PlayOnLinux and I have
never actually used just wine. I was having issues with POL and getting
steamcmd to run so I looked for alternatives and that is where I found your
application. I honestly don't think the issues I ran into were directly
related to your application and more my lack on knowledge and having a
whole bunch of different things installed on my system.
That being said here is what I ran into:
When running that command with my parameters in it, it wouldn't activate on
the Wine 6.0.3 version installed on my system. So after some research I
found where WineGUI runs off the local wine version so I upgraded to the
8.0.1 (I think) from winehq because I also found that wineprefix is
unstable / unsupported with 6.0.3.
Then I attempted to run the application and it would start but then it
would fail. So, then I attempted to make a whole new machine in WineGUI and
it would fail on the steamcmd application needed to download the vrising
server application. It would give me an error saying that 250MB more
storage space was needed to update the application.
I have been working on this most of the day today and I ended up removing
everything, including wine, and starting over fresh and was actually able
to get steamcmd installed and then use it to install the vrising server
though it is running with regular wine. Plus I was able to create a script
with the info you gave me and now it will load when I reboot my system.

**Comment by melroy89** [comment]
You could just start the server by executing the `VRisingServer.exe` file directly: `wine VRisingServer.exe`. 

There is also a bat file present I think called `start_server_example.bat`, which can be execute via either: `wine start <bat file>` or `wine cmd /c <bat file>`

And of course the `WINEPREFIX=...` can still be put in front of all the `wine` commands.

**Comment by rdnckreaper** [comment]
I tried that and it wouldn't load the files in that prefix. It actually
created a .wine folder and built a completely new instance of wine. Even
though I was trying to run it from the folder in the .winegui folder it
wouldn't access those files for some reason.
