### ISSUE TITLE
WINE details of a prefix

### ISSUE THREAD

**Issue by NovA-80** [winegui/WineGUI#14]
The main panel of a WineGUI window shows some details on the selected wineprefix. For a 64-bit prefix there seems to be an inconsistency:
```
Windows: Windows 7 (64-bit)
[...]
Wine Version: 8.9 (32-bit)
```
I suppose the 'Wine version' should show the WINEARCH, which is '64-bit' in this case.

**Comment by melroy89** [comment]
Actually no, the "32-bit" behind the Wine version is showing WineGUI is in fact using the Wine 32-bit executable on your machine.

You can change by global settings to use wine64 binary instead, that option is called "Prefer Wine 64-bit". But keep in mind `wine64` will not run 32 bit Wine bottles.

As far as I know the Wine 32-bit version can actually also make 64 bit bottles. After all the default `wine` binary is 32-bit, but still I'm able to create 64-bit bottles with this binary:

![image](https://github.com/winegui/WineGUI/assets/628926/3dad6f29-a5b5-4c0a-b4ad-c5a2cc6f42ee)

The `WINEARCH`, which is used during creation of the Wine bottle, is shown behind the 'Windows:' as you correctly identified already. So your Wine Bottle is indeed a 64-bit bottle.

**Comment by NovA-80** [comment]
Ok, I see now. Thanks for clarification. I thought that WINEARCH=64 is processed by wine64. Now, it's unclear for me, what is wine64 for. :) Anyway, it's not about WineGUI...

**Comment by melroy89** [comment]
Wine64 is a pure 64 bit binary for running Wine. Which can't run 32 bit bottles. But maybe in the future, nobody want to run 32 bit bottles? I don't know either..
