### ISSUE TITLE
scripts/build_prod.sh requires root permission?

### ISSUE THREAD

**Issue by mio-19** [winegui/WineGUI#16]
I want to build the deb package with scripts/build_prod.sh and got this
```
      |         ~~~~~~~~~~~^~~~~~
/home/user/WineGUI/src/helper.cc: In static member function ‘static std::string Helper::exec_error_message(const char*)’:
/home/user/WineGUI/src/helper.cc:1541:95: note: returned from ‘FILE* popen(const char*, const char*)’
 1541 |   std::unique_ptr<FILE, decltype(&close_exec_stream)> pipe(popen(cmd, "r"), &close_exec_stream);
      |                                                                                               ^
[20/20] Linking CXX executable bin/winegui
INFO: Building packages...
CPack: Create package using TGZ
CPack: Install projects
CPack: - Install project: WineGUI []
CMake Error at /home/user/WineGUI/build_prod/cmake_install.cmake:54 (file):
  file INSTALL cannot copy file
  "/home/user/WineGUI/src/schema/org.melroy.winegui.gschema.xml" to
  "/usr/share/glib-2.0/schemas/org.melroy.winegui.gschema.xml": Permission
  denied.


Failed to create file “/usr/share/glib-2.0/schemas/gschemas.compiled.E5ME61”: Permission denied
CPack Error: Error when generating package: WineGUI
```

**Comment by melroy89** [comment]
Yes it does, because the `build_prod.sh` is also building the packages like the .deb file using CPack.

Schemas are copied to the correct locations before cpack makes the package.

Maybe I should introduce an additional build flag to turn off/on the CPack packaging?

**Comment by melroy89** [comment]
Can I ask.. what was the reason to build from source? 

For Linux there are prebuild binaries available: https://gitlab.melroy.org/melroy/winegui/-/releases (deb, rpm and tar.gz)

**Comment by melroy89** [comment]
As stated earlier you can download the prebuild packages already from [releases](https://gitlab.melroy.org/melroy/winegui/-/releases). Just download the "WineGUI Debian Package (deb)" file.

However, if users want to build from source, I did now introduce `-Dpackage` option as well, which is by default OFF. https://gitlab.melroy.org/melroy/winegui/-/merge_requests/32
