### ISSUE TITLE
No MacOS support?

### ISSUE THREAD

**Issue by hel1o-wor1d** [winegui/WineGUI#17]
No MacOS support?

**Comment by melroy89** [comment]
Well, I wrote WIneGUI using GTK framework, which should be cross-platform with MacOS.

But no I did not yet create a MacOS binary. You could try to build it yourself under Mac. Are you using M1/M2 or Intel CPU?

**Comment by hel1o-wor1d** [comment]
Old Intel CPU Mac.

use flutter or electron instead of gtk

**Comment by melroy89** [comment]
No, I already use gtk now. 😉 Electron is btw for web apps like build around html/js/css. Which winegui isn't.

**Comment by melroy89** [comment]
Since you have a Mac, you are free to help me get it compiled under a Mac OS X system.

**Comment by melroy89** [comment]
I don't own a Mac. And I'm not planning either. No response. I'll close it.
