### ISSUE TITLE
[suggestion] desktop shortcuts and more

### ISSUE THREAD

**Issue by dull4h4n** [winegui/WineGUI#18]
Not sure if this is the right place for suggestion. First, this is a really great app. I struggled to manually install components in so many prefixes, especially if they were 32bit because I could not get winetricks (or figure out how) to install to a 32bit prefix.

A few things that would be nice would be shortcut creation so we have a .desktop that just loads our game to the menu (.local/share/applications) so we don't have to open the app. I know i can create this myself, but its ultimately something anyone using the app would eventually have to do that could be automated.

Other things would be a way of getting specific versions of wine/wine staging like Playonlinux does. That way I can modify them for older software/games and get things running.

It would also be nice to have access to all the settings that playonlinux where you can easily toggle things like CSMT or GLSL etc.

Thanks again.

**Comment by melroy89** [comment]
Yes, this repo on GitHub is just a mirror. So all the issues are here: https://gitlab.melroy.org/melroy/winegui/-/issues

Including your proposal about additional wine versions: https://gitlab.melroy.org/melroy/winegui/-/issues/22

It's indeed a good idea to have this option to create a shortcut in your menu. Actually WineGUI is reading the desktop files, did you know? WineGUI is trying to display the icons used in the desktop files within the `~/.local/share/applications/wine` directory. 

So depending on the application or game you installed, it some cases you have the option it will be added to your menu actually. Under XFCE for instance the apps/games are displayed under the Wine top-level menu item.

![image](https://github.com/winegui/WineGUI/assets/628926/32614e07-75e1-49aa-af77-0a881e8eef7d)

**Comment by melroy89** [comment]
Ps. Besides the fact WineGUI reading the shortcuts created by the Windows application. WineGUI also have has a feature to manually add a shortcut to the app list.
