### ISSUE TITLE
Could not find winetricks executable!

### ISSUE THREAD

**Issue by ahkimkoo** [winegui/WineGUI#19]
···bash
/usr/bin/winegui                
Could not find winetricks executable!
···

ubuntu22.04

**Comment by melroy89** [comment]
This is normal at the first start-up.. It should download the winetricks binary afterward this message for you automatically.

Do you face any problems? I don't think so.

**Comment by melroy89** [comment]
I will improve the stdout output message. https://gitlab.melroy.org/melroy/winegui/-/merge_requests/19
