### ISSUE TITLE
Winegui 1.5.2 on Linux Mint 20.1: Review

### ISSUE THREAD

**Issue by ggustaf** [winegui/WineGUI#2]
**Review 11 June 2021**
New install LM 20.1, wineHQ install of wine 6.0 (latest debian package).
**New** (Create new prefix):   ---  OK
**Run Program**: Added app = WinEdt 10.3, latest version from WinEdt.org   ---  OK
    WinEdt 10.3 runs. It is known to run as Gold under Linux after some settings changes, which are not minor.
    Required:   Linux TexLive,  Linux xchm ,  Windows SumatraPDF,  Linux shell scripts.
### Settings:
  **Fallback Tools**:    ---   OK
  **Supporting Tools**:    ---   OK
  **Additional Packages**:   ---    OK
      No DirectX installs.
      Installed .NET 4.0 because WinEdt had mono and gecko issues when launching
      hh.exe to view help file WinEdt.chm. Floating point overflow in xul.dll killed the app.
      After starting WinEdt anew, trying to view WinEdt.chm had the same error. Work-around
      is a Linux script to launch Linux xchm instead of hh.exe.   

**Open C: Drive**: FAIL, opened Linux xed
**Edit**: FAIL, opened an empty window with title "Edit Machine - ..."
**Reboot**: No message, no change to running app, don't know what it did.
**Update Config**: Seemed to work. Guess: Mono and Gecko were re-installed. However, no change to .NET settings in winecfg.
**Kill Processes**: OK. Unexpected was a FAIL when **Settings** window was open.
**Help** button: OK.  I expected to find here the URL of the GitHub project.

**Comment by ggustaf** [comment]
**Open C: Drive: FAIL, opened Linux xed**
**Reason:** Footbridge Troll changed PDF default for xdg-open to xed. Not the fault of winegui code. Re-test OK.

**Comment by ggustaf** [comment]
1.  Certainly "Run Program" is a major feature nicely implemented, only positive results in using it. After using winegui for a few days I found "Run Program" clumsy due to programs needing command line args.   Wine 6.0. and Winegui 1.5.2.

2. A START button like in VirtualBox is useful because it allows Windows habits to be used, like double-click to run an app. 
Assume prefix "test" has "Virtual Desktop"  1920x1080. An editable START button might be by default
  WINEPREFIX="$HOME/.winegui/prefixes/test" wine explorer /desktop=shell,1920x1080  explorer "c:"

3. "Settings" has an Install/Uninstall which does not match the Control Panel "Add/Remove Programs".  Wine 4.0.
  For instance, winegui 1.5.2 launched Install/Uninstall with only Geck0 32bit showing. The control panel  "Add/Remove Programs" in the desktop showed TotalCommander, Gecko 32bit, Gecko64bit, Mono.

**Comment by melroy89** [comment]
Hi Grant,

Thanks for your thorough study and testing of WineGUI. I'm aware of most of the 'issues', which are more todo's.

See also the GitLab project, which do contains the issue list: https://gitlab.melroy.org/melroy/winegui (I'm not using GitHub issues). And the project is still in development.

That being said, I try to create new tickets for the issues do mention that need additional care. 

Regards,
Melroy van den Berg

**Comment by melroy89** [comment]
> Edit: FAIL, opened an empty window with title "Edit Machine - ..."

Well that is now fixed today! I implemented the edit machine window ([**v.1.7.2**](https://gitlab.melroy.org/melroy/winegui/-/releases))

Maybe you wanna test it again?

> Reboot: No message, no change to running app, don't know what it did.

You should now receive an info message.

> Kill Processes: OK. Unexpected was a FAIL when Settings window was open.

This is no longer possible. Should not fail (anymore). Also you should now receive an info message.

> "Settings" has an Install/Uninstall which does not match the Control Panel "Add/Remove Programs".

I don't see any issues. WineGUI is executing: `wine uninstaller` under the hood. What command are you executing? Again, maybe test with the latest WineGUI release?

> Help button: OK. I expected to find here the URL of the GitHub project.

Done 😄 

I also implemented  the Preferences Window. Including console output logging to disk is possible.

**Comment by melroy89** [comment]
Again you are free to test the latest release!

I'm closing this issue now. Thanks for your help.

**Comment by ggustaf** [comment]
> On May 29, 2022, at 13:54, Melroy van den Berg wrote
> Again you are free to test the latest release!
Dear Melroy,
A few days ago I installed and tested the latest winegui. It was not a careful evaluation but I did check all the options. Well done. 
Grant Gustafson

**Comment by melroy89** [comment]
Thanks
