### ISSUE TITLE
Registry/windows version errors/bugs

### ISSUE THREAD

**Issue by u0-a63** [winegui/WineGUI#21]
When I try to create a new machine in WineGUI, it gives me 2 errors: 'Could not open registry file!' and 'Something went wrong while setting another Windows version. Could not set Windows OS version'. I'm trying to create a 64-bit Windows 8.1 WINE prefix with a 1366x768 virtual desktop set. Please fix this!

**Comment by melroy89** [comment]
Take it easy. What is your wine version?

Also can you try windows 7 64-bit or xp?

**Comment by u0-a63** [comment]
My Wine version is 8.0 and WineGUI says it's a 32-bit install of WINE even though I have a 64-bit system.

Windows 7 64bit works and Windows XP 64bit throws the same 2 errors.

**Comment by melroy89** [comment]
Yes winegui (and just plain wine) will always use the wine 32-bit version by default. That is fine. Wine 32-bit version can create 64-bit wine bottles. This can be changed at the preferences setting of winegui. But my advise is to leave that as as.

Instead we need to figure out why you get those errors. I'm using winetricks under the hood to set a different windows version.

**Comment by u0-a63** [comment]
I do have Winetricks installed, but how do I open a WineGUI bottle in it? Winetricks works but WineGUI seems bugged.

**Comment by melroy89** [comment]
OK. I just released v2.3.1 which add error logging to stdout terminal: https://gitlab.melroy.org/melroy/winegui/-/releases/v2.3.1.

Once you have this latest version installed, you can close WineGUI (if you had it still running). Then open a **terminal** and run WineGUI from the terminal window by typing: `winegui`. And press enter.

Finally, you can create a Windows 8.1 64-bit bottle, and hopefully you see the error logging in the terminal that I added. Now you can copy and paste the terminal output from your window to this ticket.

Hopefully this gives us more insides of what could be the root-cause. Thanks in advance for helping to find the root-cause of this issue.

**Comment by u0-a63** [comment]
This is the log I get:
```
(winegui:7871): Gtk-WARNING **: 16:33:01.216: Theme parsing error: gtk-dark.css:3877:20: '' is not a valid color name
Error: Couldn't update Winetricks script. Winetricks path: /home/u0/.local/share/winegui/winetricks, output: 1
WARN: Could not update Winetricks, keep using the v20240105
Error: Could not open and/or read from URI. Operation not supported
Error: Couldn't set Windows OS version. Wine prefix path: /home/u0/.local/share/winegui/prefixes/bottle, Winetricks path: /home/u0/.local/share/winegui/winetricks, to Windows version: Windows 8.1(Winetricks string: win81), output: 1
Error: Couldn't open registry file during get_reg_meta_data(). Trying to read from file: /home/u0/.local/share/winegui/prefixes/bottle/user.reg(using meta value name: arch)
```
In case you're wondering, I'm using CutefishOS (Debian 12) which is fully updated.

**Comment by melroyvandenberg** [comment]
As you can see, I'm use Winetricks located at `/home/u0/.local/share/winegui/winetricks`. Despite the update error, Winetricks seems to be just the latest version (v20240105).

And as you can see, it does try to set the Windows 8.1 version (Win8.1) on your created Wine bottle (called `bottle`), located at:  `/home/u0/.local/share/winegui/prefixes/bottle`.

So try the following command manually (which is actually exactly the same as [what WineGUI is trying to do for you](https://gitlab.melroy.org/melroy/winegui/-/blob/main/src/helper.cc?ref_type=heads#L1151)):

```sh
WINEPREFIX=/home/u0/.local/share/winegui/prefixes/bottle /home/u0/.local/share/winegui/winetricks win81
```

Let's see what happens or if you get any output/message/output when running this command manually in the command line?  Assuming you still have this Wine bottle called `bottle` machine present on your PC.

**Comment by u0-a63** [comment]
Just tested the latest version on Fedora 39 with Wine 9.0 staging. It works fine with no errors now.
Edit: One thing that's strange is that WineGUI is seeing a Windows 10 64-bit bottle as a Windows 8.1 64-bit bottle. That's probably because the version of Wine I'm using is a staging build, compared to a stable build.

**Comment by melroy89** [comment]
> Edit: One thing that's strange is that WineGUI is seeing a Windows 10 64-bit bottle as a Windows 8.1 64-bit bottle. That's probably because the version of Wine I'm using is a staging build, compared to a stable build.

Retrieving the Windows version is a bit tricky under Wine to be honest. Both Winetricks & `winecfg` can lead to different results in various Windows registry values. But you're right, I notice this as well I think. I'm still using Wine 8, which doesn't yet support Windows 10 ><..

See related code (get_windows_version): https://github.com/winegui/WineGUI/blob/main/src/helper.cc#L589


EDIT: I will soon try out Void Linux, which should come with [Wine 9.1 by default](https://voidlinux.org/packages/?arch=x86_64&q=wine).

**Comment by u0-a63** [comment]
Update: The issue is back. I'm on Zorin OS 17 and even after installing the `winetricks` package, the same 2 errors are popping up.
![Screenshot from 2024-02-05 19-23-29](https://github.com/winegui/WineGUI/assets/152740557/9bb8edfe-4748-4a84-af42-0cb8d1eb35df)
Please help...

**Comment by melroy89** [comment]
Again winetricks is installed by winegui on another location. You can run winegui from the command line to get debug output to your console / terminal. 

Then try to follow: https://github.com/winegui/WineGUI/issues/21#issuecomment-1916900584

EDIT:

I don't see any errors myself using WineGUI on Zorin OS 17 (I installed it in a VirtualBox VM).

![image](https://github.com/winegui/WineGUI/assets/628926/bef2ca69-c975-4764-9a14-8d5a135edb55)

It's also using Wine 8.0.2, but it seems like Winetricks will not set the machine to Windows 10. It seems to stay at Windows 7. But no errors like you have.

**Comment by u0-a63** [comment]
It seems that this error is specific to Debian/Ubuntu based distros, as I have not had any issues with this on Fedora.
![Snapshot_2024-02-17_10-52-56](https://github.com/winegui/WineGUI/assets/152740557/95d64b5c-64be-42e2-9bed-c35a0cd70fd1)
Maybe it's because Debian/Ubuntu based distros usually do not have a `winetricks` package that you can install easily.

**Comment by melroy89** [comment]
No. First of all, I'm using Linux Mint which is based on Ubuntu. And I don't see those errors.

Secondly winegui is downloading its own version of winetricks. It doesn't have a dependency for winetricks using the package manager. This is what I tried to explain earlier already as well.

**Comment by melroy89** [comment]
Anyhow, I can replicate the problem now under Zorin OS.

![image](https://github.com/winegui/WineGUI/assets/628926/38bff2b2-314d-49a5-8e08-b6cd6886ade0)

Manually runner Winetricks on this Wine bottle gave me:

![image](https://github.com/winegui/WineGUI/assets/628926/6168426c-2a26-4d7e-913f-1e13bde15561)

There is a bug in Winetricks. It seems that Winetricks is trying to use `wine64` binary, which is not present in `/usr/bin`, on some distributions Wine is compiled in a new way that the `wine` become is actually a wrapper script. 

---

**Workaround:**  `sudo ln -s /usr/bin/wine /usr/bin/wine64`

---

See: https://github.com/Winetricks/winetricks/issues/2119 and https://github.com/Winetricks/winetricks/issues/2084  and PR https://github.com/Winetricks/winetricks/pull/2035 ...

See also: https://askubuntu.com/questions/1478478/winetricks-wine-cmd-exe-c-echo-appdata-returned-empty-string-error-message

**Comment by u0-a63** [comment]
That makes sense, if Winetricks has the bug how is WineGUI supposed to work around it?

**Comment by melroy89** [comment]
Workaround now is: `sudo ln -s /usr/bin/wine /usr/bin/wine64`
