### ISSUE TITLE
[v2.4.1] [AUR] Build error "ignoring attributes on template argument"

### ISSUE THREAD

**Issue by MichielVanDerWinden** [winegui/WineGUI#23]
The following line gives an error when building from AUR: https://github.com/winegui/WineGUI/blame/061b5942268271ea5fddeb881ade2bc291441c2a/src/helper.cc#L1623

The error itself:
```
[19/21] Building CXX object CMakeFiles/winegui.dir/src/helper.cc.o
FAILED: CMakeFiles/winegui.dir/src/helper.cc.o 
/usr/bin/c++  -I/usr/include/gtkmm-3.0 -I/usr/lib/gtkmm-3.0/include -I/usr/include/atkmm-1.6 -I/usr/lib/atkmm-1.6/include -I/usr/include/gtk-3.0/unix-print -I/usr/include/gdkmm-3.0 -I/usr/lib/gdkmm-3.0/include -I/usr/include/giomm-2.4 -I/usr/lib/giomm-2.4/include -I/usr/include/gtk-3.0 -I/usr/include/cairo -I/usr/include/atk-1.0 -I/usr/include/pangomm-1.4 -I/usr/lib/pangomm-1.4/include -I/usr/include/glibmm-2.4 -I/usr/lib/glibmm-2.4/include -I/usr/include/cairomm-1.0 -I/usr/lib/cairomm-1.0/include -I/usr/include/sigc++-2.0 -I/usr/lib/sigc++-2.0/include -I/usr/include/pango-1.0 -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/cloudproviders -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/pixman-1 -I/usr/include/fribidi -I/usr/include/libpng16 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/sysprof-6 -I/home/michiel/.cache/yay/winegui/src/winegui-v2.4.1/include -I/home/michiel/.cache/yay/winegui/src/winegui-v2.4.1/build_prod -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -flto=auto -Wall -Wextra -Werror -O3 -DNDEBUG -O3 -DNDEBUG -std=c++20 -pthread -MD -MT CMakeFiles/winegui.dir/src/helper.cc.o -MF CMakeFiles/winegui.dir/src/helper.cc.o.d -o CMakeFiles/winegui.dir/src/helper.cc.o -c /home/michiel/.cache/yay/winegui/src/winegui-v2.4.1/src/helper.cc
/home/michiel/.cache/yay/winegui/src/winegui-v2.4.1/src/helper.cc: In static member function ‘static std::string Helper::exec(const char*)’:
/home/michiel/.cache/yay/winegui/src/winegui-v2.4.1/src/helper.cc:1623:42: error: ignoring attributes on template argument ‘int (*)(FILE*)’ [-Werror=ignored-attributes]
 1623 |   std::unique_ptr<FILE, decltype(&pclose)> pipe(popen(cmd, "r"), &pclose);
      |                                          ^
cc1plus: all warnings being treated as errors
```

Can't really find a reason why it ran into this as this specific function hasn't been changed in forever it seems. Still, not sure what to do about it to fix it locally. Am I missing a library or package?

I'm currently still running 2.1.0 as I was waiting for a new AUR release.

**Comment by melroy89** [comment]
Today I'm now added as Co maintainer. Let's see if I can update the package.

**Comment by melroy89** [comment]
Just a small update. I can at least replicate the issue within my VM. I suspect a new gcc compiler which new fancy features might cause this message. I need to see what is wrong with `std::unique_ptr<FILE, decltype(&pclose)>`..

![image](https://github.com/winegui/WineGUI/assets/628926/f7e8141d-61a8-4ace-80dc-f4dd2384bf55)

**Comment by melroy89** [comment]
Another update.. I got it resolved:

![image](https://github.com/winegui/WineGUI/assets/628926/653b9ba2-4161-4d36-bc31-ccf4cd1bcf75)


Next.. I will now try to update the AUR package itself ;)

**Comment by melroy89** [comment]
@MichielVanDerWinden I also rolled-out v2.4.2 now to AUR myself. Can you test it? Can confirm if it works for you now?

https://aur.archlinux.org/packages/winegui

Alvast bedankt.

**Comment by melroy89** [comment]
@MichielVanDerWinden ps ps. I also love your articles like: https://mvdwinden.nl/posts/software-setup-for-cloud-engineering-and-development/ . WineGUI is not yet part of your list, hopefully it will be soon 🥳 ..

Without the need for Windows 🤮

**Comment by MichielVanDerWinden** [comment]
> @MichielVanDerWinden I also rolled-out v2.4.2 now to AUR myself. Can you test it? Can confirm if it works for you now?
> 
> https://aur.archlinux.org/packages/winegui
> 
> Alvast bedankt.

Just updated again and it works now, thanks! :)

> @MichielVanDerWinden ps ps. I also love your articles like: https://mvdwinden.nl/posts/software-setup-for-cloud-engineering-and-development/ . WineGUI is not yet part of your list, hopefully it will be soon 🥳 ..
> 
> Without the need for Windows 🤮

Haha thanks for reading! Good one; I'll add it to the list. For now I'm only really using it to run a couple of older games that aren't available on Steam and thus no Proton support, but I love how easy WineGUI makes it to set up everything.
