### ISSUE TITLE
error while opening. taking huge time when the update site is not accessible.

### ISSUE THREAD

**Issue by shres58tha** [winegui/WineGUI#25]
when  site  **https://winegui.melroy.org/latest_release.txt** unreachable it takes very very long time to open the application and it does not respone at all freezing the computer. with prompt that wineGUI is not responding kill or wait .

**Comment by melroy89** [comment]
So sorry to hear. Yeah, that is not good. I need to write this backend call in a seperate non blocking thread.

**Comment by shres58tha** [comment]
Thank you for your reply,
i am not so good at c++ programming but putting time out of about 5 sec will work too. I will try to code something up to put this idea to test but not sure if i am capable to do this or not, i was able to disable the check and compile it so as to make it run.
and will get to you soon.

**Comment by melroy89** [comment]
I understand. Indeed a 5 second time-out might also work. But I don't like hanging GUIs. So I introduced a separate thread with dispatchers and everything.

See PR: https://gitlab.melroy.org/melroy/winegui/-/merge_requests/34

I will now validate the code, do some internal review myself. And hopefully release a new version soon.

**Comment by melroy89** [comment]
It is fixed, validated and WineGUI should hopefully never again hang on this version check. Version 2.4.3 is out!
