### ISSUE TITLE
Winegui on older platforms

### ISSUE THREAD

**Issue by ShonkaiDJ** [winegui/WineGUI#26]
Hey wonderful creator. In November last year I took a deep dive into wine. I have been trying to find out if a fully equipped media creator & 3D Linux Workstation would be in reach for myself, but moreover for people I know who would love to step away from windows and adobe but their professional environment rely on their compatibility. For years I tried several Linus distributions on a virtual machine, hyper-v on my windows workstation and laptop. Since last year I turned it around when Ableton 10/11 (wine) and Resolve were available and run great in a Linux DE. So now I'm on Ubuntu with KDE running my old Windows image in Virtman when ever I still need it.

The first month I played around a lot. You may understand I like guis. And though Bottles seemed to be the new way to go, WineGUI ultimately is my favorite. Much more down to the core of wine and with that in mind a very complete gui. I need that because my technical knowledge is broad and can only be deep at certain moments. Guis speed up my needs and at the same time teach me if build correct about the deeper part.

Now, I have setup a directory on my laptop that can detect, install and update .deb packages. For two days I have been fighting with it and only one package I used for trials. WineGUI. Yesterday after a day and a half, I found out that even on a rolled back laptop, WineGUI would not update. Not from 2.1.0 to 2.4.3, not to 2.3.4, not to 2.4.0. The update process does break any install & working WineGUI.

I am a little desperate now. I see some big improvements in a very short period of time I want to praise you for but I can't. And it is likely my own doing. After all these months i don't remember exactly how I have been testing wine and it's guis. I may have build WineGUI from the repository but I do have a copy of the 2.1.0 deb file in my downloads too.

I could use some help. Not sure if it is an issue, but if I can help you somehow in return I will. Not sure how yet but I'm confident I can. Let me know what you need form me to discover why the update doesn't work. I will share what I learn of the automated update process of deb files. If we get in a good flow of conversation i may be able to help in other ways too.

So far it's just that. I noticed your metadata is getting better and better, maybe it has something to do with that. I guess I specifically need to know how to make a completely clean install.

**Comment by melroy89** [comment]
> And though Bottles seemed to be the new way to go, WineGUI ultimately is my favorite.

Bottles is **not** _the (new) way_ to go. Why do you think that would be? Bottles just an alternative software product. But thank you that you like WineGUI better as GUI and basics.

>  WineGUI would not update. Not from 2.1.0 to 2.4.3, not to 2.3.4, not to 2.4.0. The update process does break any install & working WineGUI.

Sorry to hear that. So here are 3 questions for now.

1. Maybe you want to mention _which Ubuntu version_ are you running?

Ps. I'm using Linux Mint for the record, which is using Ubuntu 22.04 under the hood.

> I am a little desperate now. I see some big improvements in a very short period of time I want to praise you for but I can't. 

Luckily you contacted me, so we can hopefully debug the problem. You could try to install [the latest deb file](https://winegui.melroy.org/downloads/WineGUI-v2.4.3.deb) and try to open a terminal. 

2. Then type `winegui` and see if it gives more output / error that might be useful for me. What do you see on the output on the terminal?
3. Finally, could you elaborate a bit more on "break any install & working WineGUI". What does exactly break? Does it open WineGUI at all? Or is your wine not working as expected? What is the exact problem you are facing when trying to run the latest version(s)?

**Comment by melroy89** [comment]
@ShonkaiDJ Could you help answering my questions above, please?

**Comment by ShonkaiDJ** [comment]
I checked and I am still researching. Running Ubuntu 20.04 with KDE and got this message, quite clear:
winegui
winegui: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by winegui)

Found I needed to add another (jammy) repo and got so many updates, I wonder if my machine will start tomorrow. I'll let you know what is going on. And always curious about what the missing package will do for me.

**Comment by ShonkaiDJ** [comment]
I tried the solution I found, realizing it would likely create problems rather than solve the one I'd like to solve. My 20.04.1 focal is not ready for jammy security updates.. The version moved forward to GLIBC_2.35 but winegui was still failing likely because more was missing and or conflicting. I did it quick and dirty, so over 300 (security) updates came from jammy and I stopped aptitude from finding conflicts at 500+. I can do these things because timeshift so far saves me every time. So back to a working WineGUI 2.1.0.

I will do some more research to find out if I can go to a higher version and will keep you updated.

**Comment by melroy89** [comment]
Since version 2.2.0 I did indeed update to the latest GCC compiler: https://gitlab.melroy.org/melroy/winegui/-/releases/v2.2.0

To please update your distribution.

**Comment by melroy89** [comment]
Maybe try to update Ubuntu 20.04 to the latest LTS release: Ubuntu 22.04.

**Comment by ShonkaiDJ** [comment]
Sorry for the long wait. Have to test now and than when I have time to fail and roll back.
I can't upgrade my Linux version that easy. Waiting for the moment I get a grip on Ansible to use it since my desktop environment took a lot of work and it will not 'port' to a next version like it did on Windows since W7. I am not complaining about it since I realize the huge difference in user-feedback and development intentions. Nevertheless, won't work.

I have version 2.3.4 (.deb) as the version closest to the one installed. I would have liked to try 2.2.0. Anyway, 2.3.4 has the same flaw with only one number in the version difference:

**LocalRepo$** winegui
winegui: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by winegui)

You latest version asks for 'GLIBC 2.35'. So for now, from what I have tried an read, if you are on 20.04 it's better to stick to the older versions of WineGUI. I tried installing from a different repository as one quick 'advise' spoke off, but it had me rollback my complete system because it was too messy what happened. I do have Timeshift like I think I mentioned before so it is not hard to test that. I also have a link to share for users and creators to get a better understanding of the libc dependency.

I think that is mainly important to understand this has to do with some sort of a security realm and is very close related to core and kernel. Best not to try fulfilling the dependency without doing the upgrade of your system. As was my hands-on experience.

If you search for the libc.so.6 version not found on quant or any other search engine, you will find its not the only app running into this dependency flaw. Here is the best quick read I found:
[](https://www.reddit.com/r/rust/comments/15nmv7v/problem_when_running_on_ubuntu_2004/)

If you could share a .deb file of version 2.2.0, I am willing to try and see if that still works. I will even test up until which version is still suitable for 20.04 if you like. For now I have to roll back to this morning to get the ol' 2.1.0 back since I cannot re-install that one. My findings so far, signing off...

**Comment by melroy89** [comment]
The new deb files are again build with a newer c++ compiler. However, since it's open source you can very easily build it from source if you are using an old compiler still.. 

1. First install build dependencies: `sudo apt install build-essential cmake ninja-build g++ libgtkmm-3.0-dev pkg-config`
2. You just download the source code of the lastest version from here: https://winegui.melroy.org/downloads/WineGUI-Source-v2.5.0.tar.gz
3. Unpack the archive.
4. Go inside the folder and open a terminal window.
5. Build:
```
cmake -GNinja -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_BUILD_TYPE=Release -B build_prod

cmake --build ./build_prod --config Release
```
6. Install: `sudo cmake --install  --build ./build_prod --config Release`

**Comment by ShonkaiDJ** [comment]
Hey Melroy. That is how I installed WineGUI the first time. But I am not a developer and don't enjoy that too much. Decided WineGUI would be the way to go because i only needed a .deb file for install. I even have a local (laptop) signed repository to auto-update debs when they come out.

So the above is for now my contribution. I'll keep using it till it breaks and hope to upgrade so I might update. ;-)
Thanks anyway!

**Comment by ShonkaiDJ** [comment]
Done if it's up to me. Cause known and not a bug, solutions available.
