### ISSUE TITLE
Provide a flatpak package for Linux

### ISSUE THREAD

**Issue by gary-host-laptop** [winegui/WineGUI#3]
One of the biggest advantages in contrast with snaps, is that flatpaks are sandboxed, and therefore this results in a more secure and private experience since it is harder for some kind of malware to attack the system, or for said application to retrieve user information without them knowing it. Another good point is that everything that's uploaded to Flathub (Flatpak's team centralized repository). Just like snaps, Flatpaks are compatible with every distribution that supports it, so you don't have to be uploading different releases, and also is becoming a more standardized option for non-based and Ubuntu based distributions alike, being adopted already by twenty five flavours of Linux, and some of them come with flatpak preinstalled out of the box (CentOS, ElementaryOS, EndlessOS, Fedora, Linux Mint, PureOS and ZorinOS).

More information:

https://flathub.org/
https://flatpak.org/
https://flatpak.org/setup/
https://docs.flatpak.org/en/latest/

**Comment by melroy89** [comment]
I fully agree if I can easily convert CMake to a platpak file. The problem is not that I don't want to, but I'm missing tooling to easily create a flatpak from my CMake project...

**Comment by gary-host-laptop** [comment]
I sadly can't help you since I am not a developer, but maybe someone at some point will, but I don't have any idea of how that works, sorry, @danger89.

**Comment by melroy89** [comment]
I don't gonna do this anytime soon now.
