### ISSUE TITLE
Flatpak?

### ISSUE THREAD

**Issue by Aqua1ung** [winegui/WineGUI#30]
How hard would it be to release a Flatpak package for WineGUI?

**Comment by Aqua1ung** [comment]
Oops, it looks like this has been discussed already. Closing.

**Comment by melroy89** [comment]
I do think it should be possible. I hope.

**Comment by Aqua1ung** [comment]
How about a Docker image?

**Comment by melroy89** [comment]
Docker? Haha no. Winegui and wine will never run in docker containers.

**Comment by melroy89** [comment]
I did introduce an AppImage now though, that should help.
