### ISSUE TITLE
Post latest version source in Github

### ISSUE THREAD

**Issue by Aqua1ung** [winegui/WineGUI#33]
@melroy89: Please post latest version source here, in Github! We got busy people looking for it, and they, unfortunately, can't be bothered to check out GitLab or other sites.

Many thanks!

**Comment by melroy89** [comment]
Well you are in luck, since the latest version of the source is also in GitHub.

**Comment by Aqua1ung** [comment]
> Well you are in luck, since the latest version of the source is also in GitHub.

You may want to check out [this thread](https://github.com/clearlinux/distribution/issues/3178) though.

**Comment by K1ngfish3r** [comment]
This issue could be renamed for better clarity imo.
