### ISSUE TITLE
wine-9.20 (Staging)

### ISSUE THREAD

**Issue by peterweissbier** [winegui/WineGUI#34]
nothing is being detected when using wine-9.20 (Staging)

![2024-11-01_02-43](https://github.com/user-attachments/assets/2d3c6725-81e3-4d64-9dd4-0213e6d3691c)

**Comment by melroy89** [comment]
I need a bit more info..

Did you got any errors or warnings? 
What Linux distribution are you running? 
How did you installed wine? 
What version of winegui are you using? 
Can you run winegui from the terminal. And copy/paste that console output to github?

**Comment by peterweissbier** [comment]
no errors, and no log when starting from terminal
arch linux
wine staging installed via pacman -S
winegui latest 2.6.6-1

**Comment by melroy89** [comment]
I think this is no error.. I believe everything is just fine! 🥳 

Try to create a new Wine Bottle (Machine) using the `+` New symbol.

**Comment by melroy89** [comment]
Just create a new machine. Use the new button you see in the GUI.

**Comment by peterweissbier** [comment]
thank you sorry for the inconvenience
