### ISSUE TITLE
Mount ISO file as CD/DVD

### ISSUE THREAD

**Issue by lammel-hub** [winegui/WineGUI#35]
Have just started using WineGUI and it is great. 

Have not been able to find "Mount drive" or similar function for ISO files. Is that missing, or where can I find that function in the GUI?

/thanks

**Comment by melroy89** [comment]
Under Linux there a several ways of mounting an iso directly in Linux. Often by just clicking right click -> mount iso from your file manager. It depends of course on the distribution you're using.

After that, you can run the executable or whatever what is on the iso via winegui. And browse the content of the iso just like a directory.

**Comment by lammel-hub** [comment]
Thanks for the quick response! Then I'll need to add that to my desktop.

27 dec. 2024 15:03:57 Melroy van den Berg ***@***.***>:

**Comment by melroy89** [comment]
There is also the mount command under Linux.

**Comment by lammel-hub** [comment]
Thanks, but the point for me to use WineGUI is to use a gui rather than tetminal.

**Comment by melroy89** [comment]
Well. Then say which linux distribution you're using and which graphical environment.

**Comment by lammel-hub** [comment]
That is very kind, but I think I should figure it out via the OS forum rather than spend your efforts here, as the issue I need to address is not part of WineGUI.

Thanks again.
