### ISSUE TITLE
error when trying to create new machine

### ISSUE THREAD

**Issue by boredzoomr** [winegui/WineGUI#4]
![image](https://user-images.githubusercontent.com/83361414/166172971-2e6d32a9-61dc-4f9b-8ee6-09478dcf063b.png)

**Comment by melroy89** [comment]
Could you try to run the command it shows you in your terminal manually? And show me the output of the terminal.

**Comment by boredzoomr** [comment]
> Could you try to run the command it shows you in your terminal manually? And show me the output of the terminal.

ehm i think i found what i did wrong :/ i havent installed wine yet edit: rn im installing wine

**Comment by melroy89** [comment]
Well. That could be a problem Yea. Maybe I should improve the message in that case.

**Comment by boredzoomr** [comment]
> Well. That could be a problem Yea. Maybe I should improve the message in that case.

yeah i just realised that its a gui and not the entire package edit: yeah works now edit: how do i close a issue

**Comment by melroy89** [comment]
So what was the root issue? A missing wine installation or something else?

**Comment by boredzoomr** [comment]
> So what was the root issue? A missing wine installation or something else?

yeah i just didnt have a wine install

**Comment by melroy89** [comment]
OK. Thanks for letting me know. I will improve the code and error message. So it will catch this use case.

**Comment by melroy89** [comment]
I want to let you know that I released a new version (v1.5.4) that shows a better error message when you didn't install wine yet. ~~Download: https://gitlab.melroy.org/melroy/winegui/-/releases/v1.5.4~~

_EDIT:_ Download the latest release: https://gitlab.melroy.org/melroy/winegui/-/releases

**Comment by melroy89** [comment]
In the mean while we released even newer versions! Check it out!

https://gitlab.melroy.org/melroy/winegui/-/releases
