### ISSUE TITLE
[Bug] winetricks not work

### ISSUE THREAD

**Issue by dexter74** [winegui/WineGUI#5]
Hi,

When i create a machine, winetricks is not work because no permission executable.

Fix: sudo chmod +x $HOME/.winegui/winetricks

**Comment by melroy89** [comment]
I see. Thanks for reporting!

**Comment by melroy89** [comment]
Bonsoir. The code is already setting `chmod +x`. 
![image](https://user-images.githubusercontent.com/628926/169714101-b2997c0c-807e-48af-99cd-2fc53dbf46a6.png)

I don't know what is going wrong actually...

**Comment by melroy89** [comment]
did you really need `sudo`? Since that means you maybe where running it as root user before.

**Comment by dexter74** [comment]
It's not required sudo for folder user

**Comment by melroy89** [comment]
Well I see. Let's put it differently. Are you able to **reproduce** the problem? 

So let's say you remove the `$HOME/.winegui` folder and try it again. I'm unable to reproduce this issue myself, but I would like to know the root-cause.

EDIT: Maybe you can tell a bit more about which Linux Distro you are using, etc. ?

**Comment by melroy89** [comment]
Still waiting for a reply and more info.

Also try to install the latest version: https://gitlab.melroy.org/melroy/winegui/-/releases

**Comment by SMNFXCN** [comment]
I still get this issue. Latest version as of the time of writing this (2.1.0). I can't run winetricks in either the default wine (default wine machine) prefix or the one I created for foobar2000.
![image](https://github.com/winegui/WineGUI/assets/38541316/f070819f-bb8a-42c0-be23-f0552790bb58)
