### ISSUE TITLE
Create specific bottle for specific exe, extract icon, extract exe product name

### ISSUE THREAD

**Issue by fastrizwaan** [winegui/WineGUI#6]
Hi WineGui does not keep/remember an program. It would be nice if we can select an exe and create bottle/prefix for that exe using icon from that exe and name too.

I've created one such program using zenity. But yesterday I discovered your app. Yours is indeed good looking.

Please have a look
https://github.com/fastrizwaan/WineZGUI

We can use 
`icotuils` to `extract icon` from exe file  https://github.com/fastrizwaan/WineZGUI/blob/c7f400c70840f5c7f48120a9cbfb70681e1fa9eb/bin/winezgui-create-prefix#L49-L65
`exiftool` to grep product name, https://github.com/fastrizwaan/WineZGUI/blob/c7f400c70840f5c7f48120a9cbfb70681e1fa9eb/bin/winezgui-create-prefix#L82

You can test this and it uses flathub's flatpak wine 7.0 (more compatible and stable than distro specific staging wine)
https://github.com/fastrizwaan/flatpak-wine/issues/12#issuecomment-1140410755

**Comment by melroy89** [comment]
Thank you for your ticket. I'm aware that there is no app list with shortcuts. It's on the planning indeed. Past week I worked hard to implement preferences and bottle edit feature.

I think indeed the next important thing is to have an app list / shortcuts. With icons.

**Comment by melroy89** [comment]
And regarding the wine versions. I was focusing on automating the winehq stable package install using the official winehq repository. Depending on the distro I could automate this repo install and update to the latest stable wine binary. See my gitlab.

All gitlab issues: https://gitlab.melroy.org/melroy/winegui/-/issues?sort=created_date&state=opened

**Comment by fastrizwaan** [comment]
Hi, I've implement many features, esp. Installer support (finds exe, after installer is run) and the backup game bundle and restore is very useful for sharing. https://github.com/fastrizwaan/WineZGUI

You can add shortcuts to prefix by using "find command" see https://github.com/fastrizwaan/WineZGUI/blob/main/resources/modules/script-get-installed-exe-files

**Comment by melroy89** [comment]
I actually implemented this feature.

But I'm using the start menu items to find installed applications. Instead of going through the whole file system.

Download the latest version here: https://gitlab.melroy.org/melroy/winegui/-/releases

It will list the applications on the right side. Including the icon. 

![preview](https://gitlab.melroy.org/melroy/winegui/-/raw/master/misc/winegui_screenshots.gif)

**Comment by melroy89** [comment]
You can add items to the application list. And any application in this list (whether it was installed via some install wizard or manually added), you can create a shortcut now. Meaning you can add a link to your desktop or within your menu.
