### ISSUE TITLE
Can't find a way to add selected programs in side panel

### ISSUE THREAD

**Issue by ghost** [winegui/WineGUI#7]
I have Wine installed and a game in its Program Files folder.

Today I installed WineGUI and while I can click on "Run a Program" in the menu bar and select the program from the original Wine folder (not the WineGUI prefix), it doesn't save on the side panel like the gif demonstration in here. I have also tried completely copying the game folder from the original Wine folder to the one WineGUI uses, but it's still not there.

So,
- Can I save a program in the side bar (like the gif showing Age of Empire)?
- Can I change the default folder from the WineGUI prefix to the original Wine folder (I tried doing so, and I started getting errors like "couldn't find c drive")?

Thank you.

**Comment by melroy89** [comment]
Hi.

Well, first of all. The left side panel is **not** a list of applications/games. The left panel shows the wine bottles (machines).

On the most right side panel, the applications are shown.

**Important:** Please restore the WineGUI preference setting of the default location back. This can only give you more issues. Please set back to: `/home/YOURUSERNAME/.winegui/prefixes`

You can create a new wine machine under winegui. And install age of empires in the new winegui machine.

 _Alternatively_, you could try to copy over your current wine folder. 

1. Location you current existing wine bottle (eg. Everything inside `/home/YOURUSERNAME/.wine`), assuming your currently installed age of empires in that location. 
2. Create a new sub folder in the winegui default location: `/home/YOURUSERNAME/.winegui/prefixes`.
3. Copy all files from your current wine bottle towards this new folder.
4. Restart winegui. Or click on view menu item -> Refresh. 

I'm not fully sure an existing wine bottle like copying manually to this winegui folder will work. I think it should just work! And then this machine should be visible on the left side once you copied the whole wine folder contains to this new sub-folder in the ~/.winegui/prefixes/YOURFOLDERNAME/.


Note: if you notice there are sometimes dots before the folder names. Those folders become a hidden directory within Linux.

**Comment by ghost** [comment]
Thank you for the reply @danger89, I'll do that.

As for the left side panel, I meant the right side panel where all the applications are listed such as the file explorer and winecfg.

**Comment by melroy89** [comment]
No problem. Let me know if it's working. Or you need more help or questions.

**Comment by melroy89** [comment]
No problems? Any update?
