### ISSUE TITLE
gitlab.melroy.org is not responding

### ISSUE THREAD

**Issue by xBZZZZ** [winegui/WineGUI#8]
https://gitlab.melroy.org/melroy/winegui/-/releases is not responding, it's stuck loading

where else to get releases?

**Comment by melroy89** [comment]
Sorry we had indeed a modem issue, which is resolved by now.

**Comment by NeuHix** [comment]
It's again not responding @danger89

**Comment by melroy89** [comment]
This is correct indeed... My server is **NOT** down, however the ~~Domain register I use (https://www.antagonist.nl)~~ ICANN is f*king things up. They are now A records pointing to Amazon Global accelerator for some random reason.

I did NOT add at those A records towards Amazon.. I already try to contact Antagonist, but its weekend now... Hopefully they will respond and resolve it fast. 

Ps. I can not even remove those A DNS records either. I don't see it back in their interface. 

Example lookup check on a sub domain:

```sh
> nslookup -debug mastodon.melroy.org
Server:		127.0.0.53
Address:	127.0.0.53#53

------------
    QUESTIONS:
	mastodon.melroy.org, type = A, class = IN
    ANSWERS:
    ->  mastodon.melroy.org
	internet address = 15.197.130.221
	ttl = 900
    AUTHORITY RECORDS:
    ADDITIONAL RECORDS:
------------
Non-authoritative answer:
Name:	mastodon.melroy.org
Address: 15.197.130.221
------------
    QUESTIONS:
	mastodon.melroy.org, type = AAAA, class = IN
    ANSWERS:
    AUTHORITY RECORDS:
    ->  mastodon.melroy.org
	origin = ina1.registrar.eu
	mail addr = noreply.registrar.eu
	serial = 2016122000
	refresh = 10800
	retry = 3600
	expire = 604800
	minimum = 900
	ttl = 900
    ADDITIONAL RECORDS:
------------
```

**Comment by NeuHix** [comment]
Can you provide the relevant package in a file hosting service like GoFile or MEGA ?

**Comment by melroy89** [comment]
There was an issue with ICANN, they set my domain(s) to inactive. However, that is now all solved again.

Sorry for the inconvenience. This should not happen anymore. 



![image](https://user-images.githubusercontent.com/628926/203108280-2c482f11-8fad-4f3e-8b2f-84980762860c.png)

**Comment by Impeta** [comment]
@melroy89 Sorry to bother, but looks like your site is yet again not responding. Takes a very long time to load up.

**Comment by NeuHix** [comment]
@Impeta Well... it's working for me.
which package do you want? I can send it to you.

**Comment by melroy89** [comment]
Could be my isp. We are planning to move away from t-mobile.

**Comment by Impeta** [comment]
@melroy89 My bad for the late reply! Nevermind it, now I can get into the site! Was just on my end, I think.
> which package do you want? I can send it to you.

Thank you, but actually, I'm a Arch Linux user, and I would ideally get them off AUR, but they are sadly outdated. I know melroy would love to take ownership of them, but the AUR guy hasn't respond to him yet.

**Comment by melroy89** [comment]
> Thank you, but actually, I'm a Arch Linux user, and I would ideally get them off AUR, but they are sadly outdated. I know melroy would love to take ownership of them, but the AUR guy hasn't respond to him yet.

Correct. We need to wait 2 weeks total before the aur mailing list will handle my orhpan request. So stay with me, it will soon be transferred.

**Comment by melroy89** [comment]
Just for info, from today onwards I will also publish the build artifacts on GitHub: https://github.com/winegui/WineGUI/releases
