### ISSUE TITLE
How to access default prefix?

### ISSUE THREAD

**Issue by junglized** [winegui/WineGUI#9]
I'm not sure how to access default prefix located at ~/.wine? Is there a way to do that at all?

**Comment by melroy89** [comment]
All data is stored in `~/.winegui`, including the bottles in the sub folder prefixes within `~/.winegui`.

Although you can change this location at your will via the winegui settings.

**Comment by junglized** [comment]
If I choose ~/.wine I get a lot of errors. Probably because ~/.wine is itself a prefix, not a folder storing different prefixes. Maybe you should consider adding option of managing default prefix? That would be great.

**Comment by melroy89** [comment]
I would Not advice to change the data folder to `~/.wine`. This as you said could only give you issues.

Better would be to change it the other way around. What I mean is that you copy or move the default wine bottle into the prefixes directory of ~/.winegui.

You also might want to rename `.wine` to something else.

That being said, it could break existing shortcuts on your dekstop for example still pointing to the old location.

Supporting the default prefix is indeed a good suggestion. Thanks! I will really consider this feature.

**Comment by junglized** [comment]
I'll wait until default prefix is a feature before I start using WineGUI. I keep all of my installed Windows apps in default prefix. Other that that it's a very good app.

**Comment by melroy89** [comment]
OK. No problem. I will try to implement default prefix as soon as I can within WineGUI.

**Comment by melroy89** [comment]
MR: https://gitlab.melroy.org/melroy/winegui/-/merge_requests/10

**Comment by melroy89** [comment]
It's implemented already! New release is available (v1.9.0). You can download it here: https://gitlab.melroy.org/melroy/winegui/-/releases

**Comment by junglized** [comment]
I saw that yesterday, I wanted to try compile from source today but now I see you made deb package as well. Sh*t, that was lightning fast I have to say. Thank you!

**Comment by melroy89** [comment]
I had already deb packages available for 3 years.

**Comment by junglized** [comment]
I meant deb package for WineGUI 1.9.0. It wasn't there when I looked in the repo those 20 hours or so ago. I have to say, this app is better than Bottles. I like the ease of use and design of UI.

**Comment by melroy89** [comment]
> I meant deb package for WineGUI 1.9.0. It wasn't there when I looked in the repo those 20 hours or so ago. I have to say, this app is better than Bottles. I like the ease of use and design of UI.

Ow it has [CI/CD pipeline](https://gitlab.melroy.org/melroy/winegui/-/pipelines/4929) so it might take 1 or 2 minutes before the package is build and deployed. Sorry for the confusion.

Thanks! I also didn't like the Bottle UI, this is one of the reasons I created WineGUI as well.

**Comment by melroy89** [comment]
I know it's an old issue, but just for info. Since version 2.1.0 we changed the default location of the Wine bottles, instead of using the home folder `~/.winegui`, we use better locations now!

So config is stored in `~/.config/winegui/`, and the data including the Wine prefixes, are stored in `~/.local/share/winegui`, prefixes are in the sub-folder `prefixes`, so: `~/.local/share/winegui/prefixes`.

Just a heads-up, if somebody find this GitHub issue in the future.
